version: "3.1"

services:

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root 
    ports:
      - "8080:8080"